// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHi15sRQDXqdQhtI7HVeN6EYM-pjNcvr0',
    appId: '1:469878172225:web:19d4e1fb9efd52933174c0',
    messagingSenderId: '469878172225',
    projectId: 'mynotes-flutter-sjv',
    authDomain: 'mynotes-flutter-sjv.firebaseapp.com',
    storageBucket: 'mynotes-flutter-sjv.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfxZLcEmglxjnwoUIEVmVDlOjKMh8I98c',
    appId: '1:469878172225:android:8e6f09fb0fd04ad13174c0',
    messagingSenderId: '469878172225',
    projectId: 'mynotes-flutter-sjv',
    storageBucket: 'mynotes-flutter-sjv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJrwDQ2X-WDWgtVQMaGZw_Shi5kTCCDyQ',
    appId: '1:469878172225:ios:9199108294d0009f3174c0',
    messagingSenderId: '469878172225',
    projectId: 'mynotes-flutter-sjv',
    storageBucket: 'mynotes-flutter-sjv.appspot.com',
    iosClientId: '469878172225-f4g3990nqq5pdm4tfttgo3eld2lvu6fi.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
